   name: borf 
   channels:
     - pytorch
     - pyg
     - nvidia
     - conda-forge
     - defaults
   dependencies:
     - _libgcc_mutex
     - _openmp_mutex
     - blas
     - brotlipy
     - bzip2
     - ca-certificates
     - certifi
     - cffi
     - charset-normalizer
     - cryptography
     - cudatoolkit
     - ffmpeg
     - freetype
     - gmp
     - gnutls
     - idna
     - intel-openmp
     - jpeg
     - lame
     - lcms2
     - ld_impl_linux-64
     - libffi
     - libgcc-ng
     - libgomp
     - libiconv
     - libpng
     - libstdcxx-ng
     - libtiff
     - libwebp-base
     - lz4-c
     - mkl
     - mkl-service
     - mkl_fft
     - mkl_random
     - ncurses
     - nettle
     - numpy
     - numpy-base
     - olefile
     - openh264
     - openjpeg
     - openssl
     - pillow
     - pip
     - pycparser
     - pyopenssl
     - pysocks
     - python
     - python_abi
     - pytorch=2.4
     - pytorch-cuda
     - pytorch-scatter
     - pytorch-sparse
     - pytorch-mutex
     - readline
     - requests
     - setuptools
     - six
     - sqlite
     - tk
     - torchaudio
     - torchvision
     - torch-geometric
     - typing_extensions
     - tzdata
     - urllib3
     - wheel
     - xz
     - zlib
     - zstd
     - pip:
       - attrdict
       - cycler
       - fonttools
       - jinja2
       - joblib
       - kiwisolver
       - markupsafe
       - matplotlib
       - networkx
       - packaging
       - pandas
       - pyparsing
       - python-dateutil
       - pytz
       - scikit-learn
       - scipy
       - threadpoolctl
       - tqdm
